#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2009-2010 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
# or packager/legal/LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

# generated by wxGlade 0.6.3

import wx
import common.utils as utils
import dialogs

if False:    # Keep Pylint happy
    import gettext
    _= gettext.gettext

# begin wxGlade: extracode
# end wxGlade

class LicenseDialog(wx.Dialog):

    _ = wx.GetTranslation

    def __init__(self, *args, **kwds):
        """
        msg=MsgText - must be in utf-8 encoding or a unicode string
        """
        if not 'msg' in kwds:
            raise "msg is a required argument for LicenseDialog construction"

        # XXX: Toggle and reduce below once encodings are available
        if False:
            msg_text = utils.to_unicode(kwds['msg'])
        else:
            msg_text = utils.to_unicode(kwds['msg'], encoding='latin-1')
        del kwds['msg']

        self.tou_label = None
        self.tou_link = None
        tou_url = None
        if 'tou_url' in kwds:
            tou_url = kwds['tou_url']
            del kwds['tou_url']

        # begin wxGlade: LicenseDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.FULL_REPAINT_ON_RESIZE
        wx.Dialog.__init__(self, *args, **kwds)
        self.short_msg = wx.StaticText(self, -1, _("You must read and accept this license before proceeding."))

        if tou_url != None:
            self.tou_label = wx.StaticText(self, -1,
                 _("Use of packages from the publisher are subject to these "))
            self.tou_link = wx.HyperlinkCtrl(self, -1,
                    label=_("Terms of Use"), url=tou_url)
            self.tou_link.SetVisited(False)
            self.tou_link.SetToolTip(wx.ToolTip(tou_url))

        self.msg = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        self.msg.SetValue(msg_text)
        self.msg.SetFocus()
        self.Centre()


    def __set_properties(self):
        # begin wxGlade: LicenseDialog.__set_properties
        self.SetTitle(_("License agreement"))
        self.SetSize(wx.DLG_SZE(self, (400, 248)))
        # end wxGlade


    def __do_layout(self):
        # begin wxGlade: LicenseDialog.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        header_sizer = wx.BoxSizer(wx.VERTICAL)

        header_sizer.Add(self.short_msg, 0, wx.ALL|wx.EXPAND)
        if self.tou_label != None:
            tou_sizer = wx.BoxSizer(wx.HORIZONTAL)
            tou_sizer.Add(self.tou_label, 0, wx.ALL|wx.EXPAND)
            tou_sizer.Add(self.tou_link, 0, wx.ALL|wx.EXPAND)
            header_sizer.Add(tou_sizer, 0, wx.ALL|wx.EXPAND)
        main_sizer.Add(header_sizer, 0, wx.ALL, 12)
        main_sizer.Add(self.msg, 1, wx.ALL|wx.EXPAND, 12)

        self.SetSizer(main_sizer)
        self.Layout()
        # end wxGlade
        bpanel, dummy1, dummy2 = dialogs.make_std_dlg_btn_szr_panel(self, (
                (wx.ID_OK, _("&Accept"), _("Accept the license")),
                (wx.ID_CANCEL, _("&Decline"), _("Decline the license")),
                ))
        main_sizer.Add(bpanel, 0, wx.ALL|wx.ALIGN_RIGHT, 12)
        self.Layout()
        bpanel.MoveAfterInTabOrder(self.msg)

# end of class LicenseDialog
